name-template: 'v$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
branches:
  - 'testci'
categories:
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'test'
      - 'dependencies'
  - title: Everything else

template: |
  ## Changes
  $CHANGES
  ## Compare
  https://github.com/joaoreis/catapp/compare/$PREVIOUS_TAG...$NEXT_PATCH_VERSION
